name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Save Docker image as tar
        run: |
          docker save fastapi-app > fastapi-app.tar
          ls -l fastapi-app.tar

      - name: Ensure target directory exists and is writable
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p ~/deployments
            cd ~/deployments
            rm -f fastapi-app.tar

      - name: Copy Docker image to DigitalOcean VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "fastapi-app.tar"
          target: "~/deployments"

      - name: Deploy on DigitalOcean VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/deployments
            if [ ! -f fastapi-app.tar ]; then
              echo "Error: fastapi-app.tar not found"
              exit 1
            fi
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker rmi fastapi-app || true
            docker load < fastapi-app.tar
            if [ $? -ne 0 ]; then
              echo "Error: Failed to load Docker image"
              exit 1
            fi
            docker run -d --name fastapi-app -p 80:80 --restart always fastapi-app
            if [ $? -ne 0 ]; then
              echo "Error: Failed to start container"
              exit 1
            fi
            rm fastapi-app.tar