name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Fix permissions before creating tar
        run: |
          chmod -R 755 .
          sudo chown -R $USER:$USER .

      - name: Save Docker image as tar
        run: |
          docker save fastapi-app -o fastapi-app.tar
          chmod 644 fastapi-app.tar
          sudo chown $USER:$USER fastapi-app.tar

      - name: Ensure target directory exists and is writable
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            mkdir -p ~/deployments
            chmod 777 ~/deployments

      - name: Copy Docker image to DigitalOcean VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: "fastapi-app.tar"
          target: "~/deployments/"
          strip_components: 1

      - name: Deploy on DigitalOcean VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd ~/deployments
            chmod 644 fastapi-app.tar
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker rmi fastapi-app || true
            docker load -i fastapi-app.tar
            docker run -d --name fastapi-app -p 8000:8000 --restart always fastapi-app
            rm fastapi-app.tar